name: Check Markdown syntax and Japanese Lint

on:
  - pull_request

jobs:
  textlint:
    runs-on: Ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.sha}}

      - name: install node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: install dependencies
        run: npm ci

      - name: Run test
        run: npm run lint
